### ISSUE TITLE
shebang

### ISSUE THREAD

**Issue by friend1ws** [aokad/ecsub#1]
ecsubのコマンドラインスクリプトにshebangがないので、ecsubとやってもpython scriptとして認識されないように思う。
```
#! /user/bin/env python
```
などを入れていただけますでしょうか？

**Comment by friend1ws** [comment]
多分
```
python setup.py build install
```
ならいける。ただ、これだとpyenvと相性が悪いので、
```
pip install .
```
としたら、ダメだった。

**Comment by aokad** [comment]
https://github.com/aokad/ecsub/commit/ce74191feeecb561c4d4e93add1e016b84f482f2
