### ISSUE TITLE
v0.0.19のリリース

### ISSUE THREAD

**Issue by alumi** [aokad/ecsub#6]
PR #4 #5 をmergeいただき、誠にありがとうございました。
お手数をお掛けし大変恐縮ではございますが、 https://github.com/Genomon-Project/genomon_pipeline_cloud/pull/10 で作成した Docker イメージに更新版のecsubを利用するため、差し支えなければ `v0.0.19` のタグをpushいただけますと幸いです。
その後改めてこちらから [Genomon-Project/genomon_pipeline_cloud](https://github.com/Genomon-Project/genomon_pipeline_cloud) に v0.0.19 を使うPRを提出いたします。
何卒よろしくお願い申し上げます。

**Comment by aokad** [comment]
v0.0.19のタグを作成しました。

**Comment by alumi** [comment]
ご対応いただき誠にありがとうございました。https://github.com/Genomon-Project/genomon_pipeline_cloud/pull/12 を提出いたしました。
